### ISSUE TITLE
Neither EUR Zelda games boot up

### ISSUE THREAD

**Issue by Korenji** [shocoman/sm64ds_cpad_via_rtcom#1]
When I start Phantom Hourglass or Spirit Tracks with CPad Patch cheat code on, both through TWiLight Menu++ or from the home menu through a forwarder, they just hang on a white screen. My 3DS is a New XL model and I tried only the EUR releases.

**Comment by shocoman** [comment]
That's fine, sort of. It means that there is no RTCom on the Arm11's side.
So three possibilities:
1) You didn't use TWPatcher to patch the TWL_FIRM
2) You did, but didn't select the RTCom option there
3) You did both and there is TwlBg.cxi at "/luma/sysmodules", but TwilightMenu (or something else) temporarily removes that file from there.

Check the section "In case something doesn't work​" [here](https://gbatemp.net/threads/circle-pad-patches-for-super-mario-64-ds-and-other-games-in-twilightmenu-with-twpatcher-and-rtcom.623267/). Please write back if it helps

**Comment by Korenji** [comment]
> That's fine, sort of. It means that there is no RTCom on the Arm11's side. So three possibilities:
> 
> 1. You didn't use TWPatcher to patch the TWL_FIRM
> 2. You did, but didn't select the RTCom option there
> 3. You did both and there is TwlBg.cxi at "/luma/sysmodules", but TwilightMenu (or something else) temporarily removes that file from there.
> 
> Check the section "In case something doesn't work​" [here](https://gbatemp.net/threads/circle-pad-patches-for-super-mario-64-ds-and-other-games-in-twilightmenu-with-twpatcher-and-rtcom.623267/). Please write back if it helps

Oh my, you're right! I was so sure TwlBg.cxi was already in that folder that I didn't double check before writing here! My problem was solved by the first solution under that section.
Thank you and sorry for the false alarm.
